{% set name = "packaged" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/packaged-{{ version }}.tar.gz
  sha256: 0c9a31b921c66d313e7c1c759d9a275b43238af6000ded911cde5cc5e9eaf196

build:
  entry_points:
    - packaged=packaged.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - yen >=0.4.2

test:
  imports:
    - packaged
  commands:
    - pip check
    - packaged --help
  requires:
    - pip

about:
  home: https://github.com/tusharsadhwani/packaged
  summary: The easiest way to ship python applications.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
