{% set name = "packaged" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/packaged-{{ version }}.tar.gz
  sha256: 1fe7da9b2cb892091e5bb11329b5384f8c4659f56f73bddfba045fc1ba0b1401

build:
  entry_points:
    - packaged=packaged.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - yaspin >=2.5.0
    - python >=3.8
    - yen >=0.4.2

test:
  imports:
    - packaged
  commands:
    - pip check
    - packaged --help
  requires:
    - pip

about:
  home: https://github.com/tusharsadhwani/packaged
  summary: The easiest way to ship python applications.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
