schema_version: 1

context:
  name: packaged
  version: 0.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/packaged-${{ version }}.tar.gz
  sha256: 6c90d81373ff376b74b3b06ec6f4b1fa77191345b37385429c4f737d1b751fbf

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - packaged=packaged.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - yen >=0.4.2
    - tomli >=1.1.0

tests:
  - python:
      imports:
        - packaged
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - packaged --help

about:
  summary: The easiest way to ship python applications.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tusharsadhwani/packaged

extra:
  recipe-maintainers:
    - pavelzw
